{"uuid": "03926aa9-53d8-4c79-9b20-dae4c14b5040", "counter": 5, "stdout": "\u001b[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '/home/student/apod.png'\u001b[0m\r\n\u001b[0;31mfatal: [localhost]: FAILED! => {\"changed\": false, \"module_stderr\": \"Traceback (most recent call last):\\n  File \\\"/home/runner/.ansible/tmp/ansible-tmp-1660755561.9434998-30-31033809100835/AnsiballZ_nasa_apod.py\\\", line 107, in <module>\\n    _ansiballz_main()\\n  File \\\"/home/runner/.ansible/tmp/ansible-tmp-1660755561.9434998-30-31033809100835/AnsiballZ_nasa_apod.py\\\", line 99, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\\"/home/runner/.ansible/tmp/ansible-tmp-1660755561.9434998-30-31033809100835/AnsiballZ_nasa_apod.py\\\", line 47, in invoke_module\\n    runpy.run_module(mod_name='ansible_collections.rzfeeser.nasa_api.plugins.modules.nasa_apod', init_globals=dict(_module_fqn='ansible_collections.rzfeeser.nasa_api.plugins.modules.nasa_apod', _modlib_path=modlib_path),\\n  File \\\"/usr/lib64/python3.8/runpy.py\\\", line 207, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\\"/usr/lib64/python3.8/runpy.py\\\", line 97, in _run_module_code\\n    _run_code(code, mod_globals, init_globals,\\n  File \\\"/usr/lib64/python3.8/runpy.py\\\", line 87, in _run_code\\n    exec(code, run_globals)\\n  File \\\"/tmp/ansible_nasa_apod_payload_bfudqaj5/ansible_nasa_apod_payload.zip/ansible_collections/rzfeeser/nasa_api/plugins/modules/nasa_apod.py\\\", line 161, in <module>\\n  File \\\"/tmp/ansible_nasa_apod_payload_bfudqaj5/ansible_nasa_apod_payload.zip/ansible_collections/rzfeeser/nasa_api/plugins/modules/nasa_apod.py\\\", line 158, in main\\n  File \\\"/tmp/ansible_nasa_apod_payload_bfudqaj5/ansible_nasa_apod_payload.zip/ansible_collections/rzfeeser/nasa_api/plugins/modules/nasa_apod.py\\\", line 147, in run_module\\nFileNotFoundError: [Errno 2] No such file or directory: '/home/student/apod.png'\\n\", \"module_stdout\": \"\", \"msg\": \"MODULE FAILURE\\nSee stdout/stderr for the exact error\", \"rc\": 1}\u001b[0m", "start_line": 4, "end_line": 6, "runner_ident": "fc642e99-6fa6-41e6-8bdf-0d7b2749d7de", "event": "runner_on_failed", "pid": 25, "created": "2022-08-17T16:59:23.016217", "parent_uuid": "0242ac11-0002-1683-9d61-000000000008", "event_data": {"playbook": "playbook-example-nasa_apod.yml", "playbook_uuid": "52d6e423-41f4-4416-af7f-e48733f85380", "play": "First NASA APOD playbook", "play_uuid": "0242ac11-0002-1683-9d61-000000000006", "play_pattern": "localhost", "task": "Lookup the NASA APOD API for 2019-01-01 in std def", "task_uuid": "0242ac11-0002-1683-9d61-000000000008", "task_action": "nasa_apod", "resolved_action": "rzfeeser.nasa_api.nasa_apod", "task_args": "", "task_path": "/runner/project/playbook-example-nasa_apod.yml:12", "host": "localhost", "remote_addr": "localhost", "res": {"module_stdout": "", "module_stderr": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1660755561.9434998-30-31033809100835/AnsiballZ_nasa_apod.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1660755561.9434998-30-31033809100835/AnsiballZ_nasa_apod.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1660755561.9434998-30-31033809100835/AnsiballZ_nasa_apod.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.rzfeeser.nasa_api.plugins.modules.nasa_apod', init_globals=dict(_module_fqn='ansible_collections.rzfeeser.nasa_api.plugins.modules.nasa_apod', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_nasa_apod_payload_bfudqaj5/ansible_nasa_apod_payload.zip/ansible_collections/rzfeeser/nasa_api/plugins/modules/nasa_apod.py\", line 161, in <module>\n  File \"/tmp/ansible_nasa_apod_payload_bfudqaj5/ansible_nasa_apod_payload.zip/ansible_collections/rzfeeser/nasa_api/plugins/modules/nasa_apod.py\", line 158, in main\n  File \"/tmp/ansible_nasa_apod_payload_bfudqaj5/ansible_nasa_apod_payload.zip/ansible_collections/rzfeeser/nasa_api/plugins/modules/nasa_apod.py\", line 147, in run_module\nFileNotFoundError: [Errno 2] No such file or directory: '/home/student/apod.png'\n", "exception": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1660755561.9434998-30-31033809100835/AnsiballZ_nasa_apod.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1660755561.9434998-30-31033809100835/AnsiballZ_nasa_apod.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1660755561.9434998-30-31033809100835/AnsiballZ_nasa_apod.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.rzfeeser.nasa_api.plugins.modules.nasa_apod', init_globals=dict(_module_fqn='ansible_collections.rzfeeser.nasa_api.plugins.modules.nasa_apod', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_nasa_apod_payload_bfudqaj5/ansible_nasa_apod_payload.zip/ansible_collections/rzfeeser/nasa_api/plugins/modules/nasa_apod.py\", line 161, in <module>\n  File \"/tmp/ansible_nasa_apod_payload_bfudqaj5/ansible_nasa_apod_payload.zip/ansible_collections/rzfeeser/nasa_api/plugins/modules/nasa_apod.py\", line 158, in main\n  File \"/tmp/ansible_nasa_apod_payload_bfudqaj5/ansible_nasa_apod_payload.zip/ansible_collections/rzfeeser/nasa_api/plugins/modules/nasa_apod.py\", line 147, in run_module\nFileNotFoundError: [Errno 2] No such file or directory: '/home/student/apod.png'\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "_ansible_no_log": false, "changed": false}, "start": "2022-08-17T16:59:21.913535", "end": "2022-08-17T16:59:23.015941", "duration": 1.102406, "ignore_errors": null, "event_loop": null, "uuid": "03926aa9-53d8-4c79-9b20-dae4c14b5040"}}